"use client";

import { useEffect, useState } from "react";
import { FileBarChart } from "lucide-react";
import { Button } from "@/components/ui/button";
import { RouteScaffold } from "@/components/pages/RouteScaffold";
import { API_BASE_URL } from "@/lib/api";

type ReportSummary = {
  name: string;
  report_type: string;
  payload: Record<string, unknown>;
};

type ReportsResponse = {
  reports: ReportSummary[];
};

export default function ReportsPage() {
  const [reports, setReports] = useState<ReportSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch(`${API_BASE_URL}/api/reports`, { cache: "no-store", credentials: "include" })
      .then((res) => {
        if (!res.ok) throw new Error(`/api/reports returned ${res.status}`);
        return res.json() as Promise<ReportsResponse>;
      })
      .then((data) => {
        if (!cancelled) {
          setReports(data.reports ?? []);
          setLoading(false);
        }
      })
      .catch((err) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Failed to load reports");
          setLoading(false);
        }
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const windowLabel = (report: ReportSummary) => {
    const payload = report.payload || {};
    const window = (payload.window || {}) as Record<string, string>;
    return window.label ?? "Operational window";
  };

  return (
    <RouteScaffold title="Reports" description="Operational reports generated by the backend from persisted records." icon={FileBarChart}>
      {loading ? (
        <div className="grid gap-3 md:grid-cols-2">
          {Array.from({ length: 2 }).map((_, idx) => (
            <div key={idx} className="rounded-lg border border-[#1F2937] bg-[#111827] p-4">
              <div className="h-4 w-32 animate-pulse rounded bg-[#1F2937]" />
              <div className="mt-3 h-3 w-56 animate-pulse rounded bg-[#1F2937]" />
              <div className="mt-4 flex gap-2">
                <div className="h-8 w-14 animate-pulse rounded bg-[#1F2937]" />
                <div className="h-8 w-14 animate-pulse rounded bg-[#1F2937]" />
                <div className="h-8 w-14 animate-pulse rounded bg-[#1F2937]" />
              </div>
            </div>
          ))}
        </div>
      ) : error ? (
        <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">
          {error}
        </div>
      ) : (
        <div className="grid gap-3 md:grid-cols-2">
          {reports.map((report) => (
            <div key={report.report_type} className="rounded-lg border border-[#1F2937] bg-[#111827] p-4">
              <h2 className="text-sm font-semibold text-white">{report.name}</h2>
              <p className="mt-1 text-sm text-slate-400">{windowLabel(report)}. Generated from incidents, remediations, notifications, and metrics history.</p>
              <div className="mt-4 flex gap-2">
                {["json", "csv", "pdf"].map((format) => (
                  <Button key={format} size="sm" variant="outline" asChild>
                    <a href={`${API_BASE_URL}/api/reports/${report.report_type}/${format}`}>{format.toUpperCase()}</a>
                  </Button>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </RouteScaffold>
  );
}
