"use client";

import { useEffect, useState } from "react";
import { FileBarChart, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { RouteScaffold } from "@/components/pages/RouteScaffold";
import { SkeletonCard } from "@/components/common/Skeleton";
import { API_BASE_URL } from "@/lib/api";

type ReportSummary = {
  name: string;
  report_type: string;
  payload: Record<string, unknown>;
};

type ReportsResponse = {
  reports: ReportSummary[];
};

export default function ReportsPage() {
  const [reports, setReports] = useState<ReportSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch(`${API_BASE_URL}/api/reports`, { cache: "no-store", credentials: "include" })
      .then((res) => {
        if (!res.ok) throw new Error(`/api/reports returned ${res.status}`);
        return res.json() as Promise<ReportsResponse>;
      })
      .then((data) => { if (!cancelled) { setReports(data.reports ?? []); setLoading(false); } })
      .catch((err) => { if (!cancelled) { setError(err instanceof Error ? err.message : "Failed to load reports"); setLoading(false); } });
    return () => { cancelled = true; };
  }, []);

  const windowLabel = (report: ReportSummary) => {
    const payload = report.payload || {};
    const window = (payload.window || {}) as Record<string, string>;
    return window.label ?? "Operational window";
  };

  return (
    <RouteScaffold title="Reports" description="Operational reports generated by the backend from persisted records." icon={FileBarChart}>
      {loading ? (
        <div className="grid gap-4 md:grid-cols-2">
          {Array.from({ length: 2 }).map((_, i) => <SkeletonCard key={i} className="h-32" />)}
        </div>
      ) : error ? (
        <div className="rounded-lg border border-danger/20 bg-danger/10 p-4 text-sm text-danger">{error}</div>
      ) : (
        <div className="grid gap-4 md:grid-cols-2">
          {reports.map((report) => (
            <div key={report.report_type} className="rounded-xl border border-border/60 bg-surface-elevated/70 p-5 shadow-sm transition-all duration-200 hover:border-border hover:shadow-md">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h3 className="text-sm font-semibold text-text-primary">{report.name}</h3>
                  <p className="mt-1 text-xs text-text-secondary">{windowLabel(report)}. Generated from incidents, remediations, notifications, and metrics history.</p>
                </div>
                <FileBarChart className="size-5 text-primary shrink-0" />
              </div>
              <div className="flex gap-2">
                {["json", "csv", "pdf"].map((format) => (
                  <Button key={format} size="sm" variant="outline" asChild>
                    <a href={`${API_BASE_URL}/api/reports/${report.report_type}/${format}`} className="gap-1.5">
                      <Download className="size-3" />
                      {format.toUpperCase()}
                    </a>
                  </Button>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </RouteScaffold>
  );
}
