"""Compliance framework definitions for AegisNex."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Any


class ComplianceStatus(Enum):
    COMPLIANT = "compliant"
    NON_COMPLIANT = "non_compliant"
    NOT_APPLICABLE = "not_applicable"
    NOT_CHECKED = "not_checked"
    IN_PROGRESS = "in_progress"


@dataclass
class ComplianceControl:
    id: str
    framework: str
    category: str
    title: str
    description: str
    required_evidence: list[str] = field(default_factory=list)
    automated_check: str | None = None


@dataclass
class ComplianceFramework:
    id: str
    name: str
    version: str
    description: str
    controls: list[ComplianceControl] = field(default_factory=list)
    level: str = "standard"


@dataclass
class ComplianceResult:
    control_id: str
    status: ComplianceStatus
    evidence: list[dict[str, Any]] = field(default_factory=list)
    checked_at: str | None = None
    details: str = ""


def _utc_now() -> str:
    return datetime.now(UTC).isoformat().replace("+00:00", "Z")


ISO_27001 = ComplianceFramework(
    id="iso_27001",
    name="ISO/IEC 27001",
    version="2022",
    description="Information security management system standard covering 14 domains of controls (A.5-A.18).",
    level="international",
    controls=[
        ComplianceControl(
            id="A.5.1.1",
            framework="iso_27001",
            category="Information Security Policies",
            title="Policies for information security",
            description="A set of policies for information security shall be defined, approved, published, communicated, and acknowledged by relevant parties.",
            required_evidence=["policy_documents", "approval_records", "communication_logs"],
            automated_check="policy_exists",
        ),
        ComplianceControl(
            id="A.5.1.2",
            framework="iso_27001",
            category="Information Security Policies",
            title="Review of the policies for information security",
            description="The policies for information security shall be reviewed at planned intervals or when significant changes occur.",
            required_evidence=["policy_review_records", "change_logs"],
            automated_check="policy_review_check",
        ),
        ComplianceControl(
            id="A.6.1.1",
            framework="iso_27001",
            category="Organization of Information Security",
            title="Information security roles and responsibilities",
            description="All information security responsibilities shall be defined and allocated.",
            required_evidence=["role_definitions", "responsibility_matrix"],
            automated_check="roles_defined",
        ),
        ComplianceControl(
            id="A.6.1.2",
            framework="iso_27001",
            category="Organization of Information Security",
            title="Segregation of duties",
            description="Conflicting duties and areas of responsibility shall be segregated to reduce opportunities for unauthorized or unintentional modification or misuse of assets.",
            required_evidence=["segregation_matrix", "access_control_lists"],
            automated_check="segregation_check",
        ),
        ComplianceControl(
            id="A.7.1.1",
            framework="iso_27001",
            category="Human Resource Security",
            title="Screening",
            description="Background verification checks on all candidates for employment shall be carried out in accordance with relevant laws, regulations, and ethics.",
            required_evidence=["screening_policy", "verification_records"],
            automated_check=None,
        ),
        ComplianceControl(
            id="A.7.2.1",
            framework="iso_27001",
            category="Human Resource Security",
            title="Management responsibilities",
            description="Management shall require all employees and contractors to apply information security in accordance with established policies.",
            required_evidence=["acceptance_forms", "training_records"],
            automated_check=None,
        ),
        ComplianceControl(
            id="A.8.1.1",
            framework="iso_27001",
            category="Asset Management",
            title="Inventory of assets",
            description="Assets associated with information and information processing facilities shall be identified and an inventory of assets shall be maintained.",
            required_evidence=["asset_inventory", "asset_register"],
            automated_check="asset_inventory_check",
        ),
        ComplianceControl(
            id="A.8.2.1",
            framework="iso_27001",
            category="Asset Management",
            title="Classification of information",
            description="Information shall be classified in accordance with the organization's information classification scheme.",
            required_evidence=["classification_scheme", "labeling_policy"],
            automated_check=None,
        ),
        ComplianceControl(
            id="A.8.2.3",
            framework="iso_27001",
            category="Asset Management",
            title="Handling of assets",
            description="Procedures for handling assets shall be developed and implemented.",
            required_evidence=["handling_procedures", "asset_labels"],
            automated_check=None,
        ),
        ComplianceControl(
            id="A.9.1.1",
            framework="iso_27001",
            category="Access Control",
            title="Access control policy",
            description="An access control policy shall be established, documented, and reviewed.",
            required_evidence=["access_policy", "policy_review_records"],
            automated_check="access_policy_exists",
        ),
        ComplianceControl(
            id="A.9.1.2",
            framework="iso_27001",
            category="Access Control",
            title="Access to networks and network services",
            description="Users shall only be provided with access to the network and network services that they have been specifically authorized to use.",
            required_evidence=["network_access_policy", "authorization_records"],
            automated_check="network_access_check",
        ),
        ComplianceControl(
            id="A.9.2.1",
            framework="iso_27001",
            category="Access Control",
            title="User registration and de-registration",
            description="A formal user registration and de-registration process shall be implemented.",
            required_evidence=["user_registration_logs", "deactivation_records"],
            automated_check="user_lifecycle_check",
        ),
        ComplianceControl(
            id="A.9.2.2",
            framework="iso_27001",
            category="Access Control",
            title="User access provisioning",
            description="A formal user access provisioning process shall be implemented.",
            required_evidence=["provisioning_records", "role_assignment_logs"],
            automated_check="access_provisioning_check",
        ),
        ComplianceControl(
            id="A.9.2.3",
            framework="iso_27001",
            category="Access Control",
            title="Management of privileged access rights",
            description="The allocation and use of privileged access rights shall be restricted and controlled.",
            required_evidence=["privileged_access_list", "privilege_usage_logs"],
            automated_check="privileged_access_check",
        ),
        ComplianceControl(
            id="A.9.2.4",
            framework="iso_27001",
            category="Access Control",
            title="Management of secret authentication information of users",
            description="The allocation of secret authentication information shall be controlled through a formal management process.",
            required_evidence=["password_policy", "mfa_enforcement_records"],
            automated_check="auth_security_check",
        ),
        ComplianceControl(
            id="A.9.2.5",
            framework="iso_27001",
            category="Access Control",
            title="Review of user access rights",
            description="Management shall review users' access rights at regular intervals.",
            required_evidence=["access_review_records", "review_schedule"],
            automated_check="access_review_check",
        ),
        ComplianceControl(
            id="A.9.2.6",
            framework="iso_27001",
            category="Access Control",
            title="Removal or adjustment of access rights",
            description="The access rights of all employees and external party users shall be removed upon termination or adjusted upon change.",
            required_evidence=["access_removal_records", "termination_checklist"],
            automated_check="access_removal_check",
        ),
        ComplianceControl(
            id="A.9.3.1",
            framework="iso_27001",
            category="Access Control",
            title="Use of secret authentication information",
            description="Users shall be required to follow good security practices in the use of secret authentication information.",
            required_evidence=["password_guidelines", "awareness_materials"],
            automated_check="password_policy_check",
        ),
        ComplianceControl(
            id="A.10.1.1",
            framework="iso_27001",
            category="Cryptography",
            title="Policy on use of cryptographic controls",
            description="A policy on the use of cryptographic controls for protection of information shall be developed and implemented.",
            required_evidence=["crypto_policy", "encryption_standards"],
            automated_check="encryption_policy_check",
        ),
        ComplianceControl(
            id="A.10.1.2",
            framework="iso_27001",
            category="Cryptography",
            title="Key management",
            description="A policy on the use, protection, and lifetime of cryptographic keys shall be developed.",
            required_evidence=["key_management_policy", "key_rotation_logs"],
            automated_check="key_management_check",
        ),
        ComplianceControl(
            id="A.11.1.1",
            framework="iso_27001",
            category="Physical Security",
            title="Physical security perimeter",
            description="Security perimeters shall be defined and used to protect areas that contain information and information processing facilities.",
            required_evidence=["perimeter_documentation", "security_zone_maps"],
            automated_check=None,
        ),
        ComplianceControl(
            id="A.11.1.2",
            framework="iso_27001",
            category="Physical Security",
            title="Physical entry controls",
            description="Secure areas shall be protected by appropriate entry controls.",
            required_evidence=["entry_control_records", "access_card_logs"],
            automated_check=None,
        ),
        ComplianceControl(
            id="A.12.1.1",
            framework="iso_27001",
            category="Operations Security",
            title="Documented operating procedures",
            description="Operating procedures shall be documented and available to all users who need them.",
            required_evidence=["procedure_documents", "runbooks"],
            automated_check="procedures_documented",
        ),
        ComplianceControl(
            id="A.12.2.1",
            framework="iso_27001",
            category="Operations Security",
            title="Protection from malware",
            description="Detection, prevention, and recovery controls to protect against malware shall be implemented.",
            required_evidence=["malware_protection_config", "scanning_logs"],
            automated_check="malware_protection_check",
        ),
        ComplianceControl(
            id="A.12.3.1",
            framework="iso_27001",
            category="Operations Security",
            title="Backup of information",
            description="Backup copies of information, software, and system images shall be taken and tested regularly.",
            required_evidence=["backup_schedule", "backup_verification_logs"],
            automated_check="backup_check",
        ),
        ComplianceControl(
            id="A.12.4.1",
            framework="iso_27001",
            category="Operations Security",
            title="Event logging",
            description="Event logs recording user activities, exceptions, faults, and information security events shall be produced, kept, and regularly reviewed.",
            required_evidence=["audit_logs", "log_review_records"],
            automated_check="audit_logging_check",
        ),
        ComplianceControl(
            id="A.12.4.2",
            framework="iso_27001",
            category="Operations Security",
            title="Protection of log information",
            description="Logging facilities and log information shall be protected against tampering and unauthorized access.",
            required_evidence=["log_protection_policy", "access_control_logs"],
            automated_check="log_protection_check",
        ),
        ComplianceControl(
            id="A.12.4.3",
            framework="iso_27001",
            category="Operations Security",
            title="Administrator and operator logs",
            description="System administrator and system operator activities shall be logged.",
            required_evidence=["admin_activity_logs", "operator_logs"],
            automated_check="admin_logging_check",
        ),
        ComplianceControl(
            id="A.12.5.1",
            framework="iso_27001",
            category="Operations Security",
            title="Installation of software on operational systems",
            description="Procedures shall be implemented to control the installation of software on operational systems.",
            required_evidence=["change_management_records", "software_installation_logs"],
            automated_check="software_change_control",
        ),
        ComplianceControl(
            id="A.12.6.1",
            framework="iso_27001",
            category="Operations Security",
            title="Management of technical vulnerabilities",
            description="Information about technical vulnerabilities of information systems being used shall be obtained in a timely manner.",
            required_evidence=["vulnerability_scans", "patch_management_records"],
            automated_check="vulnerability_scan_check",
        ),
        ComplianceControl(
            id="A.12.7.1",
            framework="iso_27001",
            category="Operations Security",
            title="Information systems audit controls",
            description="Audit requirements and activities involving verification of operational systems shall be carefully planned and agreed.",
            required_evidence=["audit_plans", "audit_reports"],
            automated_check="audit_trail_check",
        ),
        ComplianceControl(
            id="A.13.1.1",
            framework="iso_27001",
            category="Communications Security",
            title="Network controls",
            description="Networks shall be managed and controlled to protect information in systems and applications.",
            required_evidence=["network_diagrams", "firewall_rules", "network_monitoring_logs"],
            automated_check="network_security_check",
        ),
        ComplianceControl(
            id="A.13.2.1",
            framework="iso_27001",
            category="Communications Security",
            title="Information transfer policies and procedures",
            description="Formal transfer policies, procedures, and controls shall be in place to protect the transfer of information.",
            required_evidence=["transfer_policy", "encryption_configuration"],
            automated_check="transfer_security_check",
        ),
        ComplianceControl(
            id="A.14.1.1",
            framework="iso_27001",
            category="Systems Acquisition Development",
            title="Information security requirements analysis",
            description="Information security related requirements shall be included in the requirements for new information systems.",
            required_evidence=["security_requirements_docs", "design_review_records"],
            automated_check=None,
        ),
        ComplianceControl(
            id="A.14.2.1",
            framework="iso_27001",
            category="Systems Acquisition Development",
            title="Secure development policy",
            description="Rules for the development of software and systems shall be established.",
            required_evidence=["secure_coding_policy", "code_review_records"],
            automated_check="secure_dev_check",
        ),
        ComplianceControl(
            id="A.15.1.1",
            framework="iso_27001",
            category="Supplier Relationships",
            title="Information security policy for supplier relationships",
            description="Information security requirements for mitigating risks associated with supplier access shall be documented.",
            required_evidence=["supplier_security_policy", "contract_reviews"],
            automated_check=None,
        ),
        ComplianceControl(
            id="A.16.1.1",
            framework="iso_27001",
            category="Incident Management",
            title="Responsibilities and procedures",
            description="Management responsibilities and procedures shall be established to ensure a quick, effective response to information security incidents.",
            required_evidence=["incident_response_plan", "incident_logs"],
            automated_check="incident_response_check",
        ),
        ComplianceControl(
            id="A.16.1.5",
            framework="iso_27001",
            category="Incident Management",
            title="Response to information security incidents",
            description="Information security incidents shall be responded to in accordance with documented procedures.",
            required_evidence=["incident_reports", "response_actions"],
            automated_check="incident_tracking_check",
        ),
        ComplianceControl(
            id="A.16.1.7",
            framework="iso_27001",
            category="Incident Management",
            title="Collection of evidence",
            description="The organization shall define and apply procedures for identification, collection, acquisition, and preservation of evidence.",
            required_evidence=["evidence_collection_procedures", "forensic_readiness_plan"],
            automated_check="evidence_preservation_check",
        ),
        ComplianceControl(
            id="A.17.1.1",
            framework="iso_27001",
            category="Business Continuity",
            title="Planning information security continuity",
            description="The organization shall determine its requirements for information security and the continuity of information security management in adverse situations.",
            required_evidence=["bcm_plan", "business_impact_analysis"],
            automated_check="bcm_plan_check",
        ),
        ComplianceControl(
            id="A.17.1.2",
            framework="iso_27001",
            category="Business Continuity",
            title="Implementing information security continuity",
            description="The organization shall establish, document, implement, and maintain processes to ensure continuity of information security.",
            required_evidence=["continuity_procedures", "test_results"],
            automated_check="continuity_check",
        ),
        ComplianceControl(
            id="A.18.1.1",
            framework="iso_27001",
            category="Compliance",
            title="Identification of applicable legislation",
            description="All relevant legislative, statutory, regulatory, and contractual requirements shall be identified.",
            required_evidence=["legal_register", "compliance_checklist"],
            automated_check="compliance_check",
        ),
        ComplianceControl(
            id="A.18.1.4",
            framework="iso_27001",
            category="Compliance",
            title="Privacy and protection of personally identifiable information",
            description="Privacy and protection of PII shall be ensured as required in relevant legislation.",
            required_evidence=["privacy_policy", "data_protection_impact_assessment"],
            automated_check="privacy_check",
        ),
    ],
)

SOC_2 = ComplianceFramework(
    id="soc_2",
    name="SOC 2",
    version="2023",
    description="Service Organization Control 2 — trust services criteria for security, availability, processing integrity, confidentiality, and privacy.",
    level="audit",
    controls=[
        ComplianceControl(
            id="CC1.1",
            framework="soc_2",
            category="Control Environment",
            title="Commitment to integrity and ethical values",
            description="The entity demonstrates a commitment to integrity and ethical values.",
            required_evidence=["code_of_conduct", "ethics_policy", "training_records"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CC1.2",
            framework="soc_2",
            category="Control Environment",
            title="Board oversight",
            description="The board of directors oversees the design and operation of internal control.",
            required_evidence=["board_charter", "meeting_minutes"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CC1.3",
            framework="soc_2",
            category="Control Environment",
            title="Organizational structure",
            description="Management establishes reporting lines and appropriate authority and responsibility.",
            required_evidence=["org_chart", "job_descriptions"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CC1.4",
            framework="soc_2",
            category="Control Environment",
            title="Commitment to competence",
            description="The entity demonstrates a commitment to recruit, develop, and retain competent individuals.",
            required_evidence=["training_programs", "competency_assessments"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CC1.5",
            framework="soc_2",
            category="Control Environment",
            title="Accountability",
            description="The entity holds individuals accountable for their internal control responsibilities.",
            required_evidence=["performance_reviews", "accountability_matrix"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CC2.1",
            framework="soc_2",
            category="Communication",
            title="Internal communication of information",
            description="Information regarding the functioning of internal control is communicated to personnel.",
            required_evidence=["communication_policy", "internal_newsletters"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CC2.2",
            framework="soc_2",
            category="Communication",
            title="External communication",
            description="The entity communicates with external parties regarding matters affecting internal control.",
            required_evidence=["external_communication_policy", "stakeholder_reports"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CC3.1",
            framework="soc_2",
            category="Risk Assessment",
            title="Risk identification and analysis",
            description="The entity identifies and analyzes risks to achieving its objectives.",
            required_evidence=["risk_assessment_docs", "risk_register"],
            automated_check="risk_assessment_check",
        ),
        ComplianceControl(
            id="CC3.2",
            framework="soc_2",
            category="Risk Assessment",
            title="Changes in the business environment",
            description="The entity identifies and assesses changes that could impact the system of internal control.",
            required_evidence=["change_management_policy", "impact_assessments"],
            automated_check="change_impact_check",
        ),
        ComplianceControl(
            id="CC4.1",
            framework="soc_2",
            category="Monitoring Activities",
            title="Ongoing and separate evaluations",
            description="The entity selects, develops, and performs ongoing and separate evaluations to ascertain whether components of internal control are present and functioning.",
            required_evidence=["monitoring_reports", "evaluation_schedule"],
            automated_check="monitoring_check",
        ),
        ComplianceControl(
            id="CC5.1",
            framework="soc_2",
            category="Control Activities",
            title="Selection and development of control activities",
            description="The entity selects and develops control activities that contribute to the mitigation of risks.",
            required_evidence=["control_matrix", "control_descriptions"],
            automated_check="control_activities_check",
        ),
        ComplianceControl(
            id="CC5.2",
            framework="soc_2",
            category="Control Activities",
            title="Technology controls",
            description="The entity selects and develops general control activities over technology.",
            required_evidence=["technology_controls_doc", "config_reviews"],
            automated_check="technology_controls_check",
        ),
        ComplianceControl(
            id="CC5.3",
            framework="soc_2",
            category="Control Activities",
            title="Policies and procedures",
            description="The entity deploys control activities through policies that establish expectations and procedures that implement those policies.",
            required_evidence=["policy_documents", "procedure_manuals"],
            automated_check="policy_deployment_check",
        ),
        ComplianceControl(
            id="A1.1",
            framework="soc_2",
            category="Additional Criteria — Security",
            title="Logical and physical access controls",
            description="The entity restricts logical and physical access to the system to authorized personnel.",
            required_evidence=["access_control_policy", "access_review_logs"],
            automated_check="access_control_check",
        ),
        ComplianceControl(
            id="A1.2",
            framework="soc_2",
            category="Additional Criteria — Security",
            title="System monitoring and protection",
            description="The entity monitors the system and takes action to protect against security incidents.",
            required_evidence=["monitoring_configuration", "incident_response_logs"],
            automated_check="system_monitoring_check",
        ),
        ComplianceControl(
            id="A1.3",
            framework="soc_2",
            category="Additional Criteria — Security",
            title="Security incident management",
            description="The entity defines and implements processes to detect, respond to, and recover from security incidents.",
            required_evidence=["incident_response_plan", "incident_logs"],
            automated_check="incident_management_check",
        ),
        ComplianceControl(
            id="A2.1",
            framework="soc_2",
            category="Additional Criteria — Availability",
            title="Availability monitoring",
            description="The entity monitors the availability of the system and takes action to maintain availability.",
            required_evidence=["uptime_monitoring", "availability_reports"],
            automated_check="availability_monitoring_check",
        ),
        ComplianceControl(
            id="A2.2",
            framework="soc_2",
            category="Additional Criteria — Availability",
            title="Backup and recovery",
            description="The entity has processes in place to back up data and recover the system.",
            required_evidence=["backup_policy", "recovery_test_results"],
            automated_check="backup_recovery_check",
        ),
        ComplianceControl(
            id="A3.1",
            framework="soc_2",
            category="Additional Criteria — Processing Integrity",
            title="Quality assurance",
            description="The entity monitors processing integrity and implements quality assurance procedures.",
            required_evidence=["qa_reports", "processing_monitoring_logs"],
            automated_check="processing_integrity_check",
        ),
        ComplianceControl(
            id="A4.1",
            framework="soc_2",
            category="Additional Criteria — Confidentiality",
            title="Confidential information protection",
            description="The entity protects confidential information in accordance with commitments and requirements.",
            required_evidence=["confidentiality_policy", "encryption_config"],
            automated_check="confidentiality_check",
        ),
        ComplianceControl(
            id="A5.1",
            framework="soc_2",
            category="Additional Criteria — Privacy",
            title="Privacy notice and consent",
            description="The entity provides notice and obtains consent for the collection and use of personal information.",
            required_evidence=["privacy_notice", "consent_records"],
            automated_check=None,
        ),
        ComplianceControl(
            id="A5.2",
            framework="soc_2",
            category="Additional Criteria — Privacy",
            title="Data minimization and retention",
            description="The entity limits the collection, use, and retention of personal information.",
            required_evidence=["retention_policy", "data_maps"],
            automated_check=None,
        ),
    ],
)

NIST_CSF = ComplianceFramework(
    id="nist_csf",
    name="NIST Cybersecurity Framework",
    version="2.0",
    description="Framework for improving critical infrastructure cybersecurity across five core functions.",
    level="framework",
    controls=[
        ComplianceControl(
            id="ID.AM-1",
            framework="nist_csf",
            category="Identify — Asset Management",
            title="Physical devices and systems inventory",
            description="Physical devices and systems within the organization are inventoried.",
            required_evidence=["device_inventory", "asset_management_system"],
            automated_check="asset_inventory_check",
        ),
        ComplianceControl(
            id="ID.AM-2",
            framework="nist_csf",
            category="Identify — Asset Management",
            title="Software platforms and applications inventory",
            description="Software platforms and applications within the organization are inventoried.",
            required_evidence=["software_inventory", "license_register"],
            automated_check="software_inventory_check",
        ),
        ComplianceControl(
            id="ID.AM-3",
            framework="nist_csf",
            category="Identify — Asset Management",
            title="Data flows mapping",
            description="Organizational communication and data flows are mapped.",
            required_evidence=["data_flow_diagrams", "network_maps"],
            automated_check=None,
        ),
        ComplianceControl(
            id="ID.RA-1",
            framework="nist_csf",
            category="Identify — Risk Assessment",
            title="Vulnerability identification",
            description="Asset vulnerabilities are identified and documented.",
            required_evidence=["vulnerability_scans", "vulnerability_database"],
            automated_check="vulnerability_scan_check",
        ),
        ComplianceControl(
            id="ID.RA-2",
            framework="nist_csf",
            category="Identify — Risk Assessment",
            title="Cyber threat intelligence",
            description="Threat and vulnerability information is received from information sharing forums.",
            required_evidence=["threat_intel_feeds", "advisory_subscriptions"],
            automated_check=None,
        ),
        ComplianceControl(
            id="ID.RM-1",
            framework="nist_csf",
            category="Identify — Risk Management",
            title="Risk management strategy",
            description="Risk management processes are established and communicated.",
            required_evidence=["risk_management_plan", "risk_register"],
            automated_check="risk_management_check",
        ),
        ComplianceControl(
            id="PR.AC-1",
            framework="nist_csf",
            category="Protect — Access Control",
            title="Identities and credentials management",
            description="Identities and credentials for authorized users are managed.",
            required_evidence=["identity_management_policy", "credential_policy"],
            automated_check="identity_management_check",
        ),
        ComplianceControl(
            id="PR.AC-2",
            framework="nist_csf",
            category="Protect — Access Control",
            title="Physical access control",
            description="Physical access to assets is managed and protected.",
            required_evidence=["physical_access_policy", "access_logs"],
            automated_check=None,
        ),
        ComplianceControl(
            id="PR.AC-3",
            framework="nist_csf",
            category="Protect — Access Control",
            title="Remote access management",
            description="Remote access is managed and secured.",
            required_evidence=["remote_access_policy", "vpn_configuration"],
            automated_check="remote_access_check",
        ),
        ComplianceControl(
            id="PR.AC-4",
            framework="nist_csf",
            category="Protect — Access Control",
            title="Access permissions management",
            description="Access permissions and authorizations are managed.",
            required_evidence=["permission_matrix", "role_definitions"],
            automated_check="permission_management_check",
        ),
        ComplianceControl(
            id="PR.AC-5",
            framework="nist_csf",
            category="Protect — Access Control",
            title="Network integrity",
            description="Network integrity is protected through network segregation.",
            required_evidence=["network_segmentation_diagrams", "firewall_configs"],
            automated_check="network_segmentation_check",
        ),
        ComplianceControl(
            id="PR.DS-1",
            framework="nist_csf",
            category="Protect — Data Security",
            title="Data at rest protection",
            description="Data-at-rest is protected.",
            required_evidence=["encryption_policy", "storage_encryption_configs"],
            automated_check="encryption_at_rest_check",
        ),
        ComplianceControl(
            id="PR.DS-2",
            framework="nist_csf",
            category="Protect — Data Security",
            title="Data in transit protection",
            description="Data-in-transit is protected.",
            required_evidence=["tls_configuration", "network_encryption_configs"],
            automated_check="tls_check",
        ),
        ComplianceControl(
            id="PR.DS-3",
            framework="nist_csf",
            category="Protect — Data Security",
            title="Asset disposal",
            description="Assets are formally managed throughout removal, transfers, and disposition.",
            required_evidence=["disposal_policy", "sanitization_records"],
            automated_check=None,
        ),
        ComplianceControl(
            id="PR.DS-4",
            framework="nist_csf",
            category="Protect — Data Security",
            title="Capacity management",
            description="Adequate capacity to ensure availability is maintained.",
            required_evidence=["capacity_plans", "resource_monitoring_logs"],
            automated_check="capacity_management_check",
        ),
        ComplianceControl(
            id="PR.DS-5",
            framework="nist_csf",
            category="Protect — Data Security",
            title="Backup of information",
            description="Backups of information are conducted, maintained, and tested.",
            required_evidence=["backup_policy", "backup_verification_logs"],
            automated_check="backup_check",
        ),
        ComplianceControl(
            id="PR.IP-1",
            framework="nist_csf",
            category="Protect — Information Protection",
            title="Configuration management",
            description="A baseline configuration of information technology is created and maintained.",
            required_evidence=["configuration_baselines", "change_management_policy"],
            automated_check="configuration_management_check",
        ),
        ComplianceControl(
            id="PR.IP-2",
            framework="nist_csf",
            category="Protect — Information Protection",
            title="System maintenance",
            description="A system maintenance policy is implemented.",
            required_evidence=["maintenance_policy", "maintenance_logs"],
            automated_check=None,
        ),
        ComplianceControl(
            id="PR.IP-12",
            framework="nist_csf",
            category="Protect — Information Protection",
            title="Vulnerability management",
            description="A vulnerability management plan is implemented.",
            required_evidence=["vulnerability_management_policy", "patch_logs"],
            automated_check="vulnerability_management_check",
        ),
        ComplianceControl(
            id="DE.AE-1",
            framework="nist_csf",
            category="Detect — Anomalies and Events",
            title="Baseline of network operations",
            description="A baseline of network operations and expected data flows is established.",
            required_evidence=["network_baseline", "traffic_profiles"],
            automated_check="network_baseline_check",
        ),
        ComplianceControl(
            id="DE.AE-2",
            framework="nist_csf",
            category="Detect — Anomalies and Events",
            title="Event detection",
            description="Events are detected and analyzed.",
            required_evidence=["detection_tools_config", "alert_logs"],
            automated_check="event_detection_check",
        ),
        ComplianceControl(
            id="DE.CM-1",
            framework="nist_csf",
            category="Detect — Continuous Monitoring",
            title="Network monitoring",
            description="The network is monitored to detect potential cybersecurity events.",
            required_evidence=["network_monitoring_config", "monitoring_alerts"],
            automated_check="network_monitoring_check",
        ),
        ComplianceControl(
            id="DE.CM-2",
            framework="nist_csf",
            category="Detect — Continuous Monitoring",
            title="Physical environment monitoring",
            description="The physical environment is monitored to detect potential cybersecurity events.",
            required_evidence=["physical_monitoring_config", "surveillance_logs"],
            automated_check=None,
        ),
        ComplianceControl(
            id="DE.CM-3",
            framework="nist_csf",
            category="Detect — Continuous Monitoring",
            title="Personnel activity monitoring",
            description="Personnel activity is monitored to detect potential cybersecurity events.",
            required_evidence=["user_monitoring_policy", "activity_logs"],
            automated_check="user_activity_monitoring_check",
        ),
        ComplianceControl(
            id="RS.MA-1",
            framework="nist_csf",
            category="Respond — Mitigation",
            title="Incident response plan execution",
            description="Incidents are responded to in accordance with the incident response plan.",
            required_evidence=["incident_response_plan", "incident_reports"],
            automated_check="incident_response_check",
        ),
        ComplianceControl(
            id="RS.CO-1",
            framework="nist_csf",
            category="Respond — Communications",
            title="Incident notification",
            description="Notifications are sent to stakeholders during incidents.",
            required_evidence=["notification_policy", "notification_logs"],
            automated_check="incident_notification_check",
        ),
        ComplianceControl(
            id="RC.RP-1",
            framework="nist_csf",
            category="Recover — Recovery Planning",
            title="Recovery plan execution",
            description="Recovery plans are executed during or after incidents.",
            required_evidence=["recovery_plan", "recovery_test_results"],
            automated_check="recovery_plan_check",
        ),
        ComplianceControl(
            id="RC.IM-1",
            framework="nist_csf",
            category="Recover — Improvements",
            title="Lessons learned",
            description="Lessons learned are incorporated into future recovery planning.",
            required_evidence=["lessons_learned_reports", "improvement_plans"],
            automated_check=None,
        ),
    ],
)

CIS_Controls = ComplianceFramework(
    id="cis_controls",
    name="CIS Critical Security Controls",
    version="8.0",
    description="Prioritized set of safeguards to protect organizations from known cyber attack vectors.",
    level="standard",
    controls=[
        ComplianceControl(
            id="CIS-1.1",
            framework="cis_controls",
            category="Inventory and Control of Enterprise Assets",
            title="Establish and maintain detailed enterprise asset inventory",
            description="Establish and maintain an accurate, detailed, and up-to-date inventory of all enterprise assets.",
            required_evidence=["asset_inventory", "inventory_tool_config"],
            automated_check="asset_inventory_check",
        ),
        ComplianceControl(
            id="CIS-1.2",
            framework="cis_controls",
            category="Inventory and Control of Enterprise Assets",
            title="Address unauthorized assets",
            description="Ensure unauthorized assets are identified and addressed.",
            required_evidence=["unauthorized_asset_reports", "remediation_logs"],
            automated_check="unauthorized_asset_check",
        ),
        ComplianceControl(
            id="CIS-2.1",
            framework="cis_controls",
            category="Inventory and Control of Software Assets",
            title="Establish and maintain a software inventory",
            description="Establish and maintain a detailed inventory of all licensed software.",
            required_evidence=["software_inventory", "license_records"],
            automated_check="software_inventory_check",
        ),
        ComplianceControl(
            id="CIS-2.2",
            framework="cis_controls",
            category="Inventory and Control of Software Assets",
            title="Ensure authorized software is allowed",
            description="Ensure only approved software is installed and executed.",
            required_evidence=["software_whitelist", "execution_policy"],
            automated_check="authorized_software_check",
        ),
        ComplianceControl(
            id="CIS-3.1",
            framework="cis_controls",
            category="Data Protection",
            title="Data inventory and classification",
            description="Establish and maintain a data inventory and classification scheme.",
            required_evidence=["data_classification_policy", "data_inventory"],
            automated_check="data_classification_check",
        ),
        ComplianceControl(
            id="CIS-3.2",
            framework="cis_controls",
            category="Data Protection",
            title="Encrypt data at rest",
            description="Encrypt sensitive data at rest.",
            required_evidence=["encryption_policy", "storage_encryption_config"],
            automated_check="encryption_at_rest_check",
        ),
        ComplianceControl(
            id="CIS-3.3",
            framework="cis_controls",
            category="Data Protection",
            title="Encrypt data in transit",
            description="Encrypt sensitive data in transit.",
            required_evidence=["tls_config", "network_encryption_policy"],
            automated_check="tls_check",
        ),
        ComplianceControl(
            id="CIS-3.4",
            framework="cis_controls",
            category="Data Protection",
            title="Backup and recovery",
            description="Establish and maintain a data backup and recovery process.",
            required_evidence=["backup_policy", "recovery_test_records"],
            automated_check="backup_check",
        ),
        ComplianceControl(
            id="CIS-4.1",
            framework="cis_controls",
            category="Secure Configuration of Enterprise Assets",
            title="Establish and maintain secure configuration processes",
            description="Establish and maintain secure configuration processes for enterprise assets.",
            required_evidence=["secure_config_policy", "baseline_configurations"],
            automated_check="secure_config_check",
        ),
        ComplianceControl(
            id="CIS-4.2",
            framework="cis_controls",
            category="Secure Configuration of Enterprise Assets",
            title="Automated configuration monitoring",
            description="Use automated tools to monitor configuration compliance.",
            required_evidence=["config_monitoring_tool", "compliance_reports"],
            automated_check="config_monitoring_check",
        ),
        ComplianceControl(
            id="CIS-5.1",
            framework="cis_controls",
            category="Account Management",
            title="Establish and maintain an inventory of accounts",
            description="Establish and maintain an inventory of all accounts.",
            required_evidence=["account_inventory", "user_register"],
            automated_check="account_inventory_check",
        ),
        ComplianceControl(
            id="CIS-5.2",
            framework="cis_controls",
            category="Account Management",
            title="Use unique passwords",
            description="Use unique passwords for all enterprise assets.",
            required_evidence=["password_policy", "password_manager_config"],
            automated_check="password_policy_check",
        ),
        ComplianceControl(
            id="CIS-5.3",
            framework="cis_controls",
            category="Account Management",
            title="Disable dormant accounts",
            description="Disable dormant accounts after a defined period of inactivity.",
            required_evidence=["account_review_logs", "account_disabled_list"],
            automated_check="dormant_account_check",
        ),
        ComplianceControl(
            id="CIS-6.1",
            framework="cis_controls",
            category="Access Control Management",
            title="Establish and maintain an access control model",
            description="Establish and maintain an access control model.",
            required_evidence=["access_control_model", "policy_documents"],
            automated_check="access_model_check",
        ),
        ComplianceControl(
            id="CIS-6.2",
            framework="cis_controls",
            category="Access Control Management",
            title="MFA enforcement",
            description="Require MFA for all administrative access and remote access.",
            required_evidence=["mfa_policy", "mfa_configuration"],
            automated_check="mfa_check",
        ),
        ComplianceControl(
            id="CIS-7.1",
            framework="cis_controls",
            category="Continuous Vulnerability Management",
            title="Vulnerability scanning",
            description="Perform automated vulnerability scans of internal enterprise assets.",
            required_evidence=["vulnerability_scan_config", "scan_reports"],
            automated_check="vulnerability_scan_check",
        ),
        ComplianceControl(
            id="CIS-7.2",
            framework="cis_controls",
            category="Continuous Vulnerability Management",
            title="Remediate vulnerabilities",
            description="Remediate detected vulnerabilities in a timely manner.",
            required_evidence=["remediation_records", "patch_management_logs"],
            automated_check="vulnerability_remediation_check",
        ),
        ComplianceControl(
            id="CIS-8.1",
            framework="cis_controls",
            category="Audit Log Management",
            title="Audit logging enabled",
            description="Ensure audit logging is enabled for all enterprise assets.",
            required_evidence=["audit_log_config", "logging_enabled_report"],
            automated_check="audit_logging_check",
        ),
        ComplianceControl(
            id="CIS-8.2",
            framework="cis_controls",
            category="Audit Log Management",
            title="Centralized log management",
            description="Collect and centralize audit logs.",
            required_evidence=["log_aggregation_config", "central_log_server"],
            automated_check="log_centralization_check",
        ),
        ComplianceControl(
            id="CIS-8.3",
            framework="cis_controls",
            category="Audit Log Management",
            title="Log retention",
            description="Retain audit logs for at least 12 months.",
            required_evidence=["retention_policy", "log_retention_config"],
            automated_check="log_retention_check",
        ),
        ComplianceControl(
            id="CIS-9.1",
            framework="cis_controls",
            category="Email and Web Browser Protections",
            title="Email filtering",
            description="Use email filtering to prevent malicious content.",
            required_evidence=["email_filter_config", "filtering_logs"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CIS-9.2",
            framework="cis_controls",
            category="Email and Web Browser Protections",
            title="DNS filtering",
            description="Use DNS filtering to block malicious domains.",
            required_evidence=["dns_filter_config", "blocked_domain_logs"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CIS-10.1",
            framework="cis_controls",
            category="Malware Defenses",
            title="Anti-malware deployment",
            description="Deploy and maintain anti-malware software on all enterprise assets.",
            required_evidence=["antimalware_config", "scan_schedule"],
            automated_check="malware_protection_check",
        ),
        ComplianceControl(
            id="CIS-10.2",
            framework="cis_controls",
            category="Malware Defenses",
            title="Behavior-based detection",
            description="Enable behavior-based malware detection.",
            required_evidence=["behavior_detection_config", "detection_alerts"],
            automated_check="behavior_detection_check",
        ),
        ComplianceControl(
            id="CIS-11.1",
            framework="cis_controls",
            category="Data Recovery",
            title="Backup automation",
            description="Automate backups of enterprise assets.",
            required_evidence=["backup_automation_config", "backup_logs"],
            automated_check="backup_automation_check",
        ),
        ComplianceControl(
            id="CIS-11.2",
            framework="cis_controls",
            category="Data Recovery",
            title="Recovery testing",
            description="Test data recovery processes at least annually.",
            required_evidence=["recovery_test_plans", "test_results"],
            automated_check="recovery_test_check",
        ),
        ComplianceControl(
            id="CIS-12.1",
            framework="cis_controls",
            category="Network Infrastructure Management",
            title="Network architecture documentation",
            description="Maintain and update network architecture diagrams.",
            required_evidence=["network_diagrams", "architecture_docs"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CIS-12.2",
            framework="cis_controls",
            category="Network Infrastructure Management",
            title="Network monitoring",
            description="Monitor network infrastructure for security events.",
            required_evidence=["network_monitoring_config", "monitoring_alerts"],
            automated_check="network_monitoring_check",
        ),
        ComplianceControl(
            id="CIS-13.1",
            framework="cis_controls",
            category="Network Monitoring and Defense",
            title="IDS/IPS deployment",
            description="Deploy intrusion detection and prevention systems.",
            required_evidence=["ids_ips_config", "detection_logs"],
            automated_check="ids_ips_check",
        ),
        ComplianceControl(
            id="CIS-13.2",
            framework="cis_controls",
            category="Network Monitoring and Defense",
            title="Network traffic analysis",
            description="Analyze network traffic for anomalies.",
            required_evidence=["traffic_analysis_tool", "anomaly_reports"],
            automated_check="traffic_analysis_check",
        ),
        ComplianceControl(
            id="CIS-14.1",
            framework="cis_controls",
            category="Security Awareness and Skills Training",
            title="Security awareness program",
            description="Establish and maintain a security awareness program.",
            required_evidence=["awareness_program_docs", "training_materials"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CIS-14.2",
            framework="cis_controls",
            category="Security Awareness and Skills Training",
            title="Phishing training",
            description="Train personnel on recognizing and reporting phishing attempts.",
            required_evidence=["phishing_simulation_results", "training_records"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CIS-15.1",
            framework="cis_controls",
            category="Service Provider Management",
            title="Service provider risk assessment",
            description="Assess and manage risks from service providers.",
            required_evidence=["vendor_risk_assessments", "contract_reviews"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CIS-16.1",
            framework="cis_controls",
            category="Application Software Security",
            title="Secure coding training",
            description="Train developers on secure coding practices.",
            required_evidence=["secure_coding_training", "code_review_records"],
            automated_check="secure_dev_check",
        ),
        ComplianceControl(
            id="CIS-16.2",
            framework="cis_controls",
            category="Application Software Security",
            title="Application vulnerability scanning",
            description="Scan applications for vulnerabilities.",
            required_evidence=["app_scan_reports", "remediation_records"],
            automated_check="app_vulnerability_check",
        ),
        ComplianceControl(
            id="CIS-17.1",
            framework="cis_controls",
            category="Incident Response Management",
            title="Incident response plan",
            description="Establish and maintain an incident response plan.",
            required_evidence=["ir_plan_documents", "plan_review_records"],
            automated_check="incident_response_check",
        ),
        ComplianceControl(
            id="CIS-17.2",
            framework="cis_controls",
            category="Incident Response Management",
            title="Incident response testing",
            description="Test the incident response plan at least annually.",
            required_evidence=["tabletop_exercise_results", "drill_reports"],
            automated_check=None,
        ),
        ComplianceControl(
            id="CIS-18.1",
            framework="cis_controls",
            category="Penetration Testing",
            title="Penetration testing program",
            description="Establish and maintain a penetration testing program.",
            required_evidence=["pentest_reports", "remediation_tracking"],
            automated_check=None,
        ),
    ],
)

OWASP_ASVS = ComplianceFramework(
    id="owasp_asvs",
    name="OWASP Application Security Verification Standard",
    version="4.0.3",
    description="Framework of security requirements and verification levels for web applications.",
    level="standard",
    controls=[
        ComplianceControl(
            id="V1.1",
            framework="owasp_asvs",
            category="Architecture, Design and Threat Modeling",
            title="Secure software development lifecycle",
            description="Verify the use of a secure software development lifecycle that addresses security early in the project.",
            required_evidence=["sdlc_policy", "security_gate_docs"],
            automated_check=None,
        ),
        ComplianceControl(
            id="V1.2",
            framework="owasp_asvs",
            category="Architecture, Design and Threat Modeling",
            title="Threat modeling",
            description="Verify that threat models are created for all application components.",
            required_evidence=["threat_models", "risk_assessments"],
            automated_check=None,
        ),
        ComplianceControl(
            id="V1.3",
            framework="owasp_asvs",
            category="Architecture, Design and Threat Modeling",
            title="Security architecture",
            description="Verify that all application components are defined and have security controls.",
            required_evidence=["security_architecture_doc", "component_diagrams"],
            automated_check=None,
        ),
        ComplianceControl(
            id="V2.1",
            framework="owasp_asvs",
            category="Authentication Verification",
            title="Password strength requirements",
            description="Verify that passwords are at least 8 characters and follow strength requirements.",
            required_evidence=["password_policy", "password_config"],
            automated_check="password_strength_check",
        ),
        ComplianceControl(
            id="V2.2",
            framework="owasp_asvs",
            category="Authentication Verification",
            title="MFA enforcement",
            description="Verify that multi-factor authentication is enforced for all administrative accounts.",
            required_evidence=["mfa_policy", "mfa_config"],
            automated_check="mfa_check",
        ),
        ComplianceControl(
            id="V2.3",
            framework="owasp_asvs",
            category="Authentication Verification",
            title="Credential storage",
            description="Verify that passwords are stored using a strong adaptive and salted hashing algorithm.",
            required_evidence=["password_storage_config", "hash_algorithm_docs"],
            automated_check="password_storage_check",
        ),
        ComplianceControl(
            id="V2.4",
            framework="owasp_asvs",
            category="Authentication Verification",
            title="Rate limiting",
            description="Verify that rate limiting is in place for authentication attempts.",
            required_evidence=["rate_limit_config", "login_throttle_policy"],
            automated_check="rate_limiting_check",
        ),
        ComplianceControl(
            id="V2.5",
            framework="owasp_asvs",
            category="Authentication Verification",
            title="Session invalidation",
            description="Verify that sessions are invalidated after logout and after a period of inactivity.",
            required_evidence=["session_config", "timeout_policy"],
            automated_check="session_management_check",
        ),
        ComplianceControl(
            id="V3.1",
            framework="owasp_asvs",
            category="Session Management",
            title="Session tokens",
            description="Verify that session tokens are generated using a cryptographically secure random algorithm.",
            required_evidence=["session_token_generation", "crypto_policy"],
            automated_check="session_token_check",
        ),
        ComplianceControl(
            id="V3.2",
            framework="owasp_asvs",
            category="Session Management",
            title="Session binding",
            description="Verify that session tokens are bound to a single user agent.",
            required_evidence=["session_binding_config", "user_agent_check"],
            automated_check="session_binding_check",
        ),
        ComplianceControl(
            id="V4.1",
            framework="owasp_asvs",
            category="Access Control",
            title="Least privilege principle",
            description="Verify that the principle of least privilege is applied.",
            required_evidence=["access_control_policy", "role_matrix"],
            automated_check="least_privilege_check",
        ),
        ComplianceControl(
            id="V4.2",
            framework="owasp_asvs",
            category="Access Control",
            title="Insecure direct object reference prevention",
            description="Verify that direct object references are protected by authorization checks.",
            required_evidence=["authorization_checks", "idor_prevention_docs"],
            automated_check="idor_check",
        ),
        ComplianceControl(
            id="V4.3",
            framework="owasp_asvs",
            category="Access Control",
            title="Function-level access control",
            description="Verify that all administrative functions are protected by role-based access control.",
            required_evidence=["rbac_config", "admin_function_list"],
            automated_check="rbac_check",
        ),
        ComplianceControl(
            id="V5.1",
            framework="owasp_asvs",
            category="Validation, Sanitization and Encoding",
            title="Input validation",
            description="Verify that all input is validated on the server side.",
            required_evidence=["input_validation_policy", "validation_framework"],
            automated_check="input_validation_check",
        ),
        ComplianceControl(
            id="V5.2",
            framework="owasp_asvs",
            category="Validation, Sanitization and Encoding",
            title="Output encoding",
            description="Verify that output encoding is applied for all dynamic content.",
            required_evidence=["output_encoding_config", "xss_prevention_docs"],
            automated_check="xss_prevention_check",
        ),
        ComplianceControl(
            id="V5.3",
            framework="owasp_asvs",
            category="Validation, Sanitization and Encoding",
            title="SQL injection prevention",
            description="Verify that parameterized queries or prepared statements are used for database access.",
            required_evidence=["orm_config", "parameterized_query_policy"],
            automated_check="sqli_prevention_check",
        ),
        ComplianceControl(
            id="V5.4",
            framework="owasp_asvs",
            category="Validation, Sanitization and Encoding",
            title="File upload validation",
            description="Verify that file uploads are validated for type, size, and content.",
            required_evidence=["file_upload_policy", "upload_validation_config"],
            automated_check="file_upload_check",
        ),
        ComplianceControl(
            id="V6.1",
            framework="owasp_asvs",
            category="Stored Cryptography",
            title="Cipher configuration",
            description="Verify that cryptographic algorithms use secure modes and padding schemes.",
            required_evidence=["cipher_config", "crypto_policy"],
            automated_check="cipher_security_check",
        ),
        ComplianceControl(
            id="V6.2",
            framework="owasp_asvs",
            category="Stored Cryptography",
            title="Random number generation",
            description="Verify that all random numbers are generated using cryptographically secure random number generators.",
            required_evidence=["rng_config", "crypto_module_docs"],
            automated_check="rng_security_check",
        ),
        ComplianceControl(
            id="V6.3",
            framework="owasp_asvs",
            category="Stored Cryptography",
            title="Key management",
            description="Verify that cryptographic keys are managed securely throughout their lifecycle.",
            required_evidence=["key_management_policy", "key_rotation_logs"],
            automated_check="key_management_check",
        ),
        ComplianceControl(
            id="V7.1",
            framework="owasp_asvs",
            category="Error Handling and Logging",
            title="Error handling",
            description="Verify that error messages do not leak sensitive information.",
            required_evidence=["error_handling_policy", "error_page_config"],
            automated_check="error_handling_check",
        ),
        ComplianceControl(
            id="V7.2",
            framework="owasp_asvs",
            category="Error Handling and Logging",
            title="Audit logging",
            description="Verify that all authentication decisions, access control failures, and input validation failures are logged.",
            required_evidence=["audit_log_config", "logging_standards"],
            automated_check="audit_logging_check",
        ),
        ComplianceControl(
            id="V7.3",
            framework="owasp_asvs",
            category="Error Handling and Logging",
            title="Log integrity",
            description="Verify that logs are protected from unauthorized modification.",
            required_evidence=["log_integrity_config", "log_access_controls"],
            automated_check="log_integrity_check",
        ),
        ComplianceControl(
            id="V8.1",
            framework="owasp_asvs",
            category="Data Protection",
            title="Sensitive data in transit",
            description="Verify that sensitive data is encrypted in transit using TLS.",
            required_evidence=["tls_configuration", "certificate_management"],
            automated_check="tls_check",
        ),
        ComplianceControl(
            id="V8.2",
            framework="owasp_asvs",
            category="Data Protection",
            title="Sensitive data at rest",
            description="Verify that sensitive data is encrypted at rest.",
            required_evidence=["encryption_policy", "storage_encryption"],
            automated_check="encryption_at_rest_check",
        ),
        ComplianceControl(
            id="V8.3",
            framework="owasp_asvs",
            category="Data Protection",
            title="Data retention",
            description="Verify that data retention policies are implemented and enforced.",
            required_evidence=["retention_policy", "data_purge_logs"],
            automated_check="data_retention_check",
        ),
        ComplianceControl(
            id="V9.1",
            framework="owasp_asvs",
            category="Communication Security",
            title="TLS configuration",
            description="Verify that TLS is used for all client-server communication and uses secure versions and ciphers.",
            required_evidence=["tls_version_config", "cipher_suite_config"],
            automated_check="tls_config_check",
        ),
        ComplianceControl(
            id="V9.2",
            framework="owasp_asvs",
            category="Communication Security",
            title="Certificate validation",
            description="Verify that client-side and server-side certificates are properly validated.",
            required_evidence=["certificate_pinning_config", "certificate_validation"],
            automated_check="certificate_validation_check",
        ),
        ComplianceControl(
            id="V10.1",
            framework="owasp_asvs",
            category="Malicious Code Search",
            title="Code analysis",
            description="Verify that source code is analyzed for malicious code and backdoors.",
            required_evidence=["static_analysis_reports", "code_review_records"],
            automated_check="static_analysis_check",
        ),
        ComplianceControl(
            id="V10.2",
            framework="owasp_asvs",
            category="Malicious Code Search",
            title="Dependency scanning",
            description="Verify that third-party dependencies are scanned for known vulnerabilities.",
            required_evidence=["dependency_scan_reports", "sbom_documents"],
            automated_check="dependency_scan_check",
        ),
        ComplianceControl(
            id="V11.1",
            framework="owasp_asvs",
            category="Business Logic",
            title="Business logic validation",
            description="Verify that business logic flows are validated for security concerns.",
            required_evidence=["business_logic_docs", "logic_test_cases"],
            automated_check=None,
        ),
        ComplianceControl(
            id="V11.2",
            framework="owasp_asvs",
            category="Business Logic",
            title="Rate limiting on business functions",
            description="Verify that rate limiting is applied to critical business functions.",
            required_evidence=["rate_limit_config", "business_api_throttling"],
            automated_check="rate_limiting_check",
        ),
        ComplianceControl(
            id="V12.1",
            framework="owasp_asvs",
            category="Files and Resources",
            title="File execution restrictions",
            description="Verify that uploaded files are not executable in the web root.",
            required_evidence=["file_execution_policy", "web_server_config"],
            automated_check="file_execution_check",
        ),
        ComplianceControl(
            id="V12.2",
            framework="owasp_asvs",
            category="Files and Resources",
            title="Content-type verification",
            description="Verify that content-type headers are validated for uploaded files.",
            required_evidence=["content_type_validation", "upload_policy"],
            automated_check="content_type_check",
        ),
        ComplianceControl(
            id="V13.1",
            framework="owasp_asvs",
            category="API and Web Service",
            title="API authentication",
            description="Verify that all API endpoints require authentication.",
            required_evidence=["api_auth_policy", "auth_middleware_config"],
            automated_check="api_auth_check",
        ),
        ComplianceControl(
            id="V13.2",
            framework="owasp_asvs",
            category="API and Web Service",
            title="API rate limiting",
            description="Verify that API rate limiting is implemented.",
            required_evidence=["api_rate_limit_config", "throttle_config"],
            automated_check="api_rate_limit_check",
        ),
        ComplianceControl(
            id="V13.3",
            framework="owasp_asvs",
            category="API and Web Service",
            title="API input validation",
            description="Verify that all API inputs are validated against a schema.",
            required_evidence=["api_schema_validation", "input_validation_policy"],
            automated_check="api_validation_check",
        ),
        ComplianceControl(
            id="V14.1",
            framework="owasp_asvs",
            category="Configuration",
            title="Secure HTTP headers",
            description="Verify that security headers (CSP, HSTS, X-Frame-Options, etc.) are configured.",
            required_evidence=["http_headers_config", "security_policy"],
            automated_check="http_headers_check",
        ),
        ComplianceControl(
            id="V14.2",
            framework="owasp_asvs",
            category="Configuration",
            title="CORS configuration",
            description="Verify that CORS headers are properly configured and restrictive.",
            required_evidence=["cors_config", "allowed_origins_list"],
            automated_check="cors_check",
        ),
        ComplianceControl(
            id="V14.3",
            framework="owasp_asvs",
            category="Configuration",
            title="Dependency version check",
            description="Verify that all library and framework dependencies are up to date.",
            required_evidence=["dependency_versions", "update_logs"],
            automated_check="dependency_version_check",
        ),
    ],
)

BUILTIN_FRAMEWORKS: dict[str, ComplianceFramework] = {
    "iso_27001": ISO_27001,
    "soc_2": SOC_2,
    "nist_csf": NIST_CSF,
    "cis_controls": CIS_Controls,
    "owasp_asvs": OWASP_ASVS,
}
